### ISSUE TITLE
[Linux/SM 1.12] Accelerator faild to upload crash dump

### ISSUE THREAD

**Issue by fbef0102** [asherkin/accelerator#31]
Download latest version in https://github.com/asherkin/accelerator/actions and test

```c
Accelerator (2.6.0-manual): SRCDS Crash Handler
```
```
Ubuntu 22.04.5 LTS
```

**Test result**
In linux
-SM v1.11 Stable Builds: fine
-SM v1.12 Stable Builds: Sorry, presubmit is required

In windows
-SM v1.11 Stable Builds: fine
-SM v1.12 Stable Builds: fine

```
[CRASH] Accelerator uploaded crash dump: Sorry, presubmit is required - you may need to upgrade accelerator or adjust your config
```

It appears to be related to the SM version.  I have to roll back 1.12 to 1.11, crash report can upload.
```
sm version
 SourceMod Version Information:
    SourceMod Version: 1.12.0.7202
    SourcePawn Engine: 1.12.0.7202, jit-x86 (build 1.12.0.7202)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: May 20 2025 18:24:53
    Built from: https://github.com/alliedmodders/sourcemod/commit/1b8a87ca
    Build ID: 7202:1b8a87ca
    http://www.sourcemod.net/
```

related #24

**Comment by godrider** [comment]
Where do we stand on this right now?

```
Response module list doesn't match sent list (33 < 87)
Uploaded crash dump: Sorry, presubmit is required - you may need to upgrade accelerator or adjust your config
```
```
 SourceMod Version Information:
    SourceMod Version: 1.13.0.7245
    SourcePawn Engine: 1.13.0.7245, jit-x86 (build 1.13.0.7245)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Jun 21 2025 13:16:15
    Built from: https://github.com/alliedmodders/sourcemod/commit/4afbf9d5
    Build ID: 7245:4afbf9d5
    http://www.sourcemod.net/
```
```
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1353
    Plugin interface version: 17:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: May 28 2025 18:31:08
    Built from: https://github.com/alliedmodders/metamod-source/commit/76f36a8
    Build ID: 1353:76f36a8
    http://www.metamodsource.net/
```

**Comment by Kenzzer** [comment]
Update on this, issue is fixed in 38f7e5d6f23330e35df7f7bcde63134382bbbc33. However Throttle continues to refuse symbols upload, this doesn't prevent crash dumps from being uploaded and processed though. Symbol upload fail is unrelated OP's issue, so I'll be closing this and opening a separate issue.

**Comment by fbef0102** [comment]
> Update on this, issue is fixed in [38f7e5d](https://github.com/asherkin/accelerator/commit/38f7e5d6f23330e35df7f7bcde63134382bbbc33). However Throttle continues to refuse symbols upload, this doesn't prevent crash dumps from being uploaded and processed though. Symbol upload fail is unrelated OP's issue, so I'll be closing this and opening a separate issue.

The #24 problem is back again
https://github.com/asherkin/accelerator/issues/34#issuecomment-3369342760
```
Accelerator upload thread started.
free(): invalid pointer
Aborted (core dumped)
```

**Comment by adriansmares** [comment]
So for the record deleting `bin/libstdc++.so.6` and `bin/libgcc_s.so.1` has not been enough for me. I still had
```
Response module list doesn't match sent list (33 < 60)
Uploaded crash dump: Sorry, presubmit is required - you may need to upgrade accelerator or adjust your config
```
in my accelerator logs. 

This was maddening to debug but the chain of things going from bad to worse seems to be:
1. Something is loading a `libstdc++.so.6`. I deleted all the instances (there are extra `libstdc++.so.6` and `libgcc_s.so.1` in `bin/dedicated` by the way) that I could find, but it didn't help. Maybe some extension is statically linked ?
2. Somehow, this breaks C++ locale loading. Specifically building the summary stream at:
https://github.com/asherkin/accelerator/blob/3ed12667984f9730ee6b25f89b53258af90c3d58/extension/extension.cpp#L849
Dies immediately after inserting the `2`. Dies in this context means that `.bad()` and `.fail()` return 1 for this stream - no inserts work afterwards. Funny things like `summaryStream.imbue(std::locale::classic());` do not work - any attempts to fix locales seems doomed to fail.

What did work, and I do not understand why, and I wish I knew why, was to do the following:
1. Move `srcds_linux` to `srcds_linux_original`.
2. Create a script called `srcds_linux` with the following contents:
```bash
#!/bin/bash

export LD_PRELOAD=/usr/lib/i386-linux-gnu/libstdc++.so.6

exec ./srcds_linux_original "$@"
```

(make sure that you have `libstdc++6:i386` installed)

This for some reason works - the summary stream is built correctly and for `sv_cheats 1; crash` I now get:
<details>

```
Got a presubmit token from server: Ignoring L4D2 sv_crash minidump
Getting module at index 0
Classified module /home/steam/srcds/srcds_linux_original as Game
UploadSymbolFile
Submitting symbols for /home/steam/srcds/srcds_linux_original
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 1
Classified module /home/steam/srcds/srcds_linux_original as Game
UploadSymbolFile
Submitting symbols for /home/steam/srcds/srcds_linux_original
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 5
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/dbi.mysql.ext.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/dbi.mysql.ext.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 8
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/geoip.ext.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/geoip.ext.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 9
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sourcetvmanager.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sourcetvmanager.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 14
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sdkhooks.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sdkhooks.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 15
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sdktools.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sdktools.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 16
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sourcetvsupport.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/sourcetvsupport.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 17
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/accelerator.ext.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/accelerator.ext.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 18
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/impactfix.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/impactfix.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 19
Classified module /home/steam/steamcmd/linux32/steamclient.so as System
UploadSymbolFile
Submitting symbols for /home/steam/steamcmd/linux32/steamclient.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 25
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/extensions/collisionhook.ext.2.l4d2.so as Extension
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/extensions/collisionhook.ext.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 31
Classified module /home/steam/srcds/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so as Addon
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 34
Classified module /home/steam/srcds/left4dead2/addons/metamod/bin/metamod.2.l4d2.so as Addon
UploadSymbolFile
Submitting symbols for /home/steam/srcds/left4dead2/addons/metamod/bin/metamod.2.l4d2.so
Symbol upload failed: The requested URL returned error: 400 (22)
Getting module at index 57
Classified module /usr/lib/i386-linux-gnu/libstdc++.so.6 as System
UploadSymbolFile
Submitting symbols for /usr/lib/i386-linux-gnu/libstdc++.so.6
Symbol upload failed: The requested URL returned error: 400 (22)
PresubmitCrashDump complete
Skipped due to server request
```

</details>

All the 400s I suppose are caused by https://github.com/asherkin/accelerator/issues/39 .

Any insights into why `LD_PRELOAD` fixes this is much appreciated. I cannot understand why in the absence of any `libstdc++.so.6` the loading is still borked.

LE: [AM Discord discussion](https://discord.com/channels/335290997317697536/335290997317697536/1444705806258802739).

LE2: My final state is that I deleted the following files:
- `bin/libstdc++.so.6`
- `bin/libgcc_s.so.1`
- `bin/dedicated/libstdc++.so.6`
- `bin/dedicated/libgcc_s.so.1`
- (if you have `steamcmd`) `steamcmd/linux32/libstdc++.so.6`

And use the following `srcds_linux` substitute script:
```bash
#!/bin/bash

export LD_PRELOAD="/usr/lib/i386-linux-gnu/libc.so.6:/usr/lib/i386-linux-gnu/libgcc_s.so.1:/usr/lib/i386-linux-gnu/libstdc++.so.6"

exec ./srcds_linux_original "$@"
```

The packages I have installed are `libc6:i386` and `libstdc++6:i386`.

**Comment by fbef0102** [comment]
> So for the record deleting `bin/libstdc++.so.6` and `bin/libgcc_s.so.1` has not been enough for me. I still had

Now I download "2.6.0-dcf3449 Linux" from https://builds.limetech.io/?p=accelerator
Server: Sourcemod 1.12 + Metamod 1.12 l4d2 server
System: ubuntu 22.04 TLS

I try your steps

1. Delete
-bin/libstdc++.so.6
-bin/libgcc_s.so.1
-bin/dedicated/libstdc++.so.6
-bin/dedicated/libgcc_s.so.1

2.  srcds_linux -> srcds_linux_original
Create a custom script "srcds_linux" to load system's standard lib
```c
#!/bin/bash
export LD_PRELOAD="/usr/lib/i386-linux-gnu/libc.so.6:/usr/lib/i386-linux-gnu/libgcc_s.so.1:/usr/lib/i386-linux-gnu/libstdc++.so.6"
exec ./srcds_linux_original "$@"
```

Crash dump fails to upload. 
It says "Accelerator crash dump upload skipped by server"
```
Got a presubmit token from server: Ignoring L4D2 sv_crash minidump
PresubmitCrashDump complete
Skipped due to server request
```

What am I doing wrong.. No idea if I am the only one who has these situations

**Comment by fbef0102** [comment]
> ```
> Got a presubmit token from server: Ignoring L4D2 sv_crash minidump
> PresubmitCrashDump complete
> Skipped due to server request
> ```
> 
> What am I doing wrong.. No idea if I am the only one who has these situations

False alarm
Now crash dump successfully uploads
```sv_cheats 1;sv_crash```
```
Got a presubmit token from server: 5fcf195ef6da8ca5e822cxxxx
PresubmitCrashDump complete
Uploaded crash dump: Crash ID: xxxxxxx
```
------
```sv_cheats 1; crash```
```
Got a presubmit token from server: Ignoring L4D2 sv_crash minidump
PresubmitCrashDump complete
Skipped due to server request
```
