### ISSUE TITLE
[Linux] Crash on startup

### ISSUE THREAD

**Issue by sapphonie** [asherkin/accelerator#34]
#### temporary fix if your server is crashing
for now to fix this, in `/addons/sourcemod/configs/core.cfg`, change `"MinidumpSymbolUpload"` to 0 instead of 3

#### todo dev stuff
- this is possibly related to module parsing
- `gdb bt` soon

**Comment by sapphonie** [comment]
I can NOT reproduce this

**Comment by sapphonie** [comment]
Hopefully fixed by #35

**Comment by sapphonie** [comment]
Looks like 
```
0x00007faa91bf0231 in char32_t std::(anonymous namespace)::read_utf8_code_point<char>(std::(anonymous namespace)::range<char const, true>&, unsigned long) ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/x64/accelerator.ext.so
(gdb) bt
#0  0x00007faa91bf0231 in char32_t std::(anonymous namespace)::read_utf8_code_point<char>(std::(anonymous namespace)::range<char const, true>&, unsigned long) ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/x64/accelerator.ext.so
#1  0x00007faa91bf119a in std::codecvt_base::result std::(anonymous namespace)::utf16_in<char, char16_t>(std::(anonymous namespace)::range<char const, true>&, std::(anonymous namespace)::range<char16_t, true>&, unsigned long, std::codecvt_mode) () from /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/x64/accelerator.ext.so
#2  0x00007faa91bf12cb in std::codecvt<char16_t, char, __mbstate_t>::do_in(__mbstate_t&, char const*, char const*, char const*&, char16_t*, char16_t*, char16_t*&) const ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/x64/accelerator.ext.so
#3  0x00007faa91bc3f9d in std::basic_ostream<char, std::char_traits<char> >& std::basic_ostream<char, std::char_traits<char> >::_M_insert<unsigned long>(unsigned long) ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/x64/accelerator.ext.so
#4  0x00007faa91aec124 in std::basic_ostream<char, std::char_traits<char> >::operator<< (__n=10385,
    this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/ostream:204
#5  google_breakpad::HexString<unsigned int> (number=10385)
    at /home/caxanga334/Documents/alliedmodders/accelerator/third_party/breakpad/src/processor/logging.h:126
#6  0x00007faa91ae72f5 in google_breakpad::MinidumpProcessor::Process (this=this@entry=0x7faa919fe2e0,
    dump=dump@entry=0x7faa919fe1a8, process_state=process_state@entry=0x7faa919fe450)
    at /home/caxanga334/Documents/alliedmodders/accelerator/third_party/breakpad/src/processor/minidump_processor.cc:264
#7  0x00007faa91aeb809 in google_breakpad::MinidumpProcessor::Process (this=0x7faa919fe2e0,
    minidump_file="/home/tf2server/serverfiles/tf/addons/sourcemod/data/dumps/6a6a7271-4cc1-465d-1c0fd6b3-8aeb6569.dmp", process_state=0x7faa919fe450)
    at /home/caxanga334/Documents/alliedmodders/accelerator/third_party/breakpad/src/processor/minidump_processor.cc:420
#8  0x00007faa91a98ea0 in UploadThread::PresubmitCrashDump (this=this@entry=0x7faa91ce7970 <uploadThread>,
    path=path@entry=0x7faa919fe860 "/home/tf2server/serverfiles/tf/addons/sourcemod/data/dumps/6a6a7271-4cc1-465d-1c0fd6b3-8aeb6569.dmp", tokenBuffer=tokenBuffer@entry=0x7faa919fea60 "", tokenBufferLength=tokenBufferLength@entry=512)
    at /home/caxanga334/Documents/alliedmodders/accelerator/extension/extension.cpp:816
#9  0x00007faa91a98b34 in UploadThread::RunThread (this=0x7faa91ce7970 <uploadThread>, pHandle=<optimized out>)
    at /home/caxanga334/Documents/alliedmodders/accelerator/extension/extension.cpp:451
#10 0x00007faaa1c9e037 in CompatThread::Run() ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/bin/x64/sourcemod.logic.so
#11 0x00007faaa1d6e3b0 in execute_native_thread_routine ()
   from /home/tf2server/serverfiles/tf/addons/sourcemod/bin/x64/sourcemod.logic.so
#12 0x00007faab3a57b7b in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:448
#13 0x00007faab3ad57b8 in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by fbef0102** [comment]
Does not fix at all, #37 issue still exist

<img width="962" height="309" alt="Image" src="https://github.com/user-attachments/assets/8b60a555-95c5-45ef-af4c-b6ee1adf5974" />

How to reproduce 
1. Launch server -> sv_cheats 1 -> crash -> auto-generate dump files in ```sourcemod/data/dumps```
2. Server crashes on start and get endless reboot.

System: L4D1 Ubuntu 22.04.5 LTS
sm version
```
 SourceMod Version Information:
    SourceMod Version: 1.12.0.7217
    SourcePawn Engine: 1.12.0.7217, jit-x86 (build 1.12.0.7217)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Oct  3 2025 13:19:04
    Built from: https://github.com/alliedmodders/sourcemod/commit/092ea91f
    Build ID: 7217:092ea91f
    http://www.sourcemod.net/
```

Accelerator version:  [Latest build](https://github.com/asherkin/accelerator/actions)
